version: '3'

volumes:
  sqlite_data:

services:
  api:
    build: ./api
    ports:
      - "80:80"
    volumes:
      - sqlite_data:/api/db
  
  bot:
    build: ./bot
    env_file: ./bot/.env
    ports:
      - "8000:8000"
    links:
      - api:api-service
  

  